The birth of the Swiss mathematician Leonhard Euler has been celebrated by Google with the publishing of an interactive Google doodle.

Euler was arguably the most important mathematician of the 18th century and one of the greatest of all time. He introduced most modern mathematical terminology and notation and was also renowned for his work in mechanics, fluid dynamics, optics, and astronomy.



<<results=tex>>==
  #source("./Scripts/test.R")
  result <- matrix(1:4, nrow=2, ncol=2)
  colnames(result) <- c("Rok", "Bieg")  
  rownames(result) <- c("Strus", "Wilk")
  result <- xtable(result)
  print(result, include.rownames=FALSE)
@


Euler was born in Basel on 15 April 1707. He was tutored by Johann Bernoulli, a family friend who was also Europe's leading mathematician. When Euler's father tried to make him become a pastor, Bernoulli persuaded him that his son had the potential to be a great mathematician.

He travelled to Russia, where he prospered until foreign intellectuals became unpopular and he moved to Berlin. When Catherine the Great succeeded to the throne, Euler returned to Russia, where he died in 1783.

